//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dqdK22CNT3Lesson07db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dqdSinhVien
    {
        public string dqdMaSV { get; set; }
        public string dqdHoSV { get; set; }
        public string dqdTenSV { get; set; }
        public Nullable<System.DateTime> dqdNgaySinh { get; set; }
        public Nullable<bool> dqdPhai { get; set; }
        public string dqdPhone { get; set; }
        public string dqdEmail { get; set; }
        public string dqdMaKH { get; set; }
    }
}
